name: Node.js CI

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting the main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies that the workflow will run on the latest Ubuntu image

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (with the version you need)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Replace with the Node.js version you need, e.g., '14', '16', or '18'
      
      - name: Change Directory
        run: cd ./cocswitch_app; ls -la; npm install; npm run build

      # Step 6: Cache node_modules (optional, speeds up subsequent runs)
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './cocswitch_app/dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


